# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3.3.0
      -
        name: Get Details
        uses: ./
        id: go-mod-details
        with:
          modfile: ${{ github.workspace }}/.github/go.mod
      -
        name: Test Version
        shell: bash
        run: |
          if [[ "${{ steps.go-mod-details.outputs.go_version }}" != "1.19" ]]; then
            echo "expected '1.19', but got '${{ steps.go-mod-details.outputs.go_version }}'"
            exit 1
          fi
      -
        name: Test Module
        shell: bash
        run: |
          if [[ "${{ steps.go-mod-details.outputs.module }}" != "main" ]]; then
            echo "expected 'main', but got '${{ steps.go-mod-details.outputs.module }}'"
            exit 1
          fi

  # use nancy to scan for vulnerabilities.
  vulnerability_scanner:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3.3.0
      -
        uses: actions/setup-go@v3
      # we cannot use nancy-github-action because it is outdated, so it's better to use the latest
      # docker image for the validation
      -
        name: nancy
        run: go list -json -m all | docker run -i sonatypecommunity/nancy:latest

  # draft your next release notes as pull requests are merged into "master"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        if: github.ref == 'refs/heads/master'
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
